// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lagjsxhrcbiopqoopwmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZ2pzeGhyY2Jpb3Bxb29wd21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDcxMjEsImV4cCI6MjA1MDk4MzEyMX0.ZFpRC2LjKhr6Tzncf9olvmPqtLETi_I8XJSk1H3PxWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);